BOVADA_COLUMNS = [
    "scrape_datetime",
    "game_datetime",
    "top_team",
    "top_final",
    "bottom_final",
    "bottom_team",
    "top_spread",
    "top_spread_odds",
    "top_ml_odds",
    "top_total",
    "top_total_odds",
    "bottom_spread",
    "bottom_spread_odds",
    "bottom_ml_odds",
    "bottom_total",
    "bottom_total_odds",
]
