# Generated by Django 3.2.9 on 2021-11-19 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(max_length=30)),
                ('datetime', models.DateTimeField()),
            ],
            options={
                'db_table': 'game',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'player',
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'sport',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbrev', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'team',
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'venue',
            },
        ),
        migrations.CreateModel(
            name='Webpage',
            fields=[
                ('url', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('body', models.TextField()),
            ],
            options={
                'db_table': 'webpage',
            },
        ),
        migrations.CreateModel(
            name='NflPlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('defensive_team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defensive_team', to='sports_app.team')),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports_app.game')),
                ('offensive_team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offensive_team', to='sports_app.team')),
            ],
            options={
                'db_table': 'nfl_play',
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports_app.sport')),
            ],
            options={
                'db_table': 'league',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='sports_app.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='sports_app.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports_app.venue'),
        ),
    ]
