# Generated by Django 3.2.8 on 2021-10-08 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamgamestat',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports_app.teamgamestattype'),
        ),
    ]
